apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "next.fullname" . }}-nginx-conf
  labels:
    {{- include "next.labels" . | nindent 4 }}
data:
  {{ $api :=  "http://apiservice/api"  -}}
  {{ $next :=  "http://next"  -}}
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      resolver 127.0.0.1:53 ipv6=off valid=10s;
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;
      server {
        listen  80;
        server_tokens off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        client_max_body_size 1000M;
        gzip on;
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_types text/css application/javascript image/svg+xml;
        set $backend {{ $api }};
        location ~ ^\/api\/(.*)$  {
          proxy_pass $backend/$1$is_args$args;
          proxy_set_header  Host $http_host;
        }
        set $frontend {{ $next }};
        location ~ ^\/(.*)$ {
          proxy_pass $frontend/$1$is_args$args;
          proxy_set_header  Host $http_host;

        }
      }
    }