apiVersion: v1
kind: Service
metadata:
  name: {{ include "next.fullname" . }}
  labels:
    {{- include "next.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: next
      protocol: TCP
      name: next
  selector:
    {{- include "next.selectorLabels" . | nindent 4 }}
